export { default as Home } from './Home'
export { default as Inventory } from './Inventory'
export { default as Ranking } from './Ranking'
export { default as Market } from './Market'
export { default as Login } from './Login'
export { default as Mint } from './Mint'
export { default as Swap } from './Swap'
export { default as Fight } from './Fight'
export {default as Lootbox} from './Lootbox'